CREATE TABLE [ROTA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORIGEM] [varchar](10) NULL,
	[DESTINO] [varchar](10) NULL,
	[VALOR] [decimal](18, 2) NULL,
 CONSTRAINT [PK_ROTA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

---------------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[LOCAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NomeLocal] [varchar](10) NULL,
 CONSTRAINT [PK_LOCAL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]